import Head from "next/head";
import Navbar from "./Navbar";

export default function Layout(props) {
  const { children } = props;
  return (
    <div>
      <Head>
        <title>Gameshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>{children}</div>
    </div>
  );
}
